# download: https://www.microsoft.com/en-us/download/details.aspx?id=11774

- name: Download Microsoft sqlJDBC driver
  ansible.builtin.get_url:
    url: "{{download_url}}"
    dest: "{{download_path}}"

- name: Unarchive file
  ansible.builtin.unarchive:
    src: "{{download_path}}"
    dest: "{{query}}/"
    remote_src: yes