# download: https://www.microsoft.com/en-us/download/details.aspx?id=11774

- name: Download Microsoft SQL JDBC driver
  ansible.builtin.get_url:
    url: "{{download_url}}"
    dest: "{{download_path}}"

- name: Create query directory
  ansible.builtin.file:
    path: "{{query}}"
    state: directory

- name: Unarchive file
  ansible.builtin.unarchive:
    src: "{{download_path}}"
    dest: "{{query}}/"
    remote_src: yes