---
# **Todo**: Make it automatically get {{name}} from {{repo}} using regex! This way I don't need an extra name field.
- hosts: localhost
  vars:
    stor: ".uni/stor/"
    query: ".uni/query/"
    repo: [
      { subdir: "{{query}}", repo: "git@github.com:Source-Graph/connectAzureSQL.git", name: "connectAzureSQL"},
      { subdir: "{{query}}", repo: "git@github.com:Uni-Apps/LibreOffice-Base.git", name: "LibreOffice-Base"},
      { subdir: "{{stor}}", repo: "git@github.com:UniStor/MinIO.git", name: "MinIO"},
      ]
  tasks:
  - debug:
      msg: "{{item.name}}"
    loop: "{{repo}}"

  - name: Git checkout
    ansible.builtin.git:
      repo: "{{item.repo}}"
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/src/{{item.subdir}}{{item.name}}"
    loop: "{{repo}}"
