# Change this file to add dependency artifacts, repos, & roles!
repo: [
  { repo: "git@github.com:Unicorn-OS/Uni.os.default.git", name: "Uni.os.default"},
  ]

role: [
  { git: "Uni.os.default", name: "uni", path: "src/ansible/roles/uni"},
  ]


# set Inventory
dynamic_inventory: "{{static_inventory}}"
