# download: https://www.microsoft.com/en-us/download/details.aspx?id=11774

- name: Download Oracle JDK 8
  ansible.builtin.get_url:
    url: "{{download_url}}"
    dest: "{{download_path}}"

- name: Create query directory
  ansible.builtin.file:
    path: "{{language}}"
    state: directory

# - name: Unarchive file
#   ansible.builtin.unarchive:
#     src: "{{download_path}}"
#     dest: "{{language}}/"
#     remote_src: yes