---
# pull in .pre dependencies
# - hosts: localhost
#   roles:
#   - .pre

# init is not needed if you're only running on localhost!
- hosts: test #,localhost
  vars:
    # Host_vars
    ansible_become_password: u
    ansible_user: "{{lookup('ansible.builtin.env', 'USER')}}"

  roles:
  # - LibreOffice Base
  # - driver/Microsoft JDBC
  - JDK8/Oracle
  - neurobin Oraji